development:
  adapter: postgresql
  encoding: unicode
  database: Sample_App_development
  host: 127.0.0.1
  user: kimardenmiller
  password:
  port: 5432
  min_messages: warning

test: &test
  adapter: postgresql
  encoding: unicode
  database: Sample_App_test
  host: 127.0.0.1
  user: kimardenmiller
  password:
  port: 5432
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: Sample_App_development
  host: 127.0.0.1
  user: root
  password:
  port: 5432
  min_messages: warning

staging:
  adapter: postgresql
  encoding: unicode
  database: Sample_App_staging
  host: 127.0.0.1
  user: kimardenmiller
  password:
  port: 5432
  min_messages: warning

cucumber:
  <<: *test